# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/vivado/Project/KTH/milestone4/milestone4.srcs/sources_1/ip/sram/sram.xci
# IP: The module: 'sram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/vivado/Project/KTH/milestone4/milestone4.srcs/sources_1/ip/sram/sram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/vivado/Project/KTH/milestone4/milestone4.srcs/sources_1/ip/sram/sram.xci
# IP: The module: 'sram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/vivado/Project/KTH/milestone4/milestone4.srcs/sources_1/ip/sram/sram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
